# -*- coding: utf-8 -*-
"""TT Exp 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WxYy75IjsOE4uyKrozFYYVWY_Pxu0eF2
"""

def find_winner(n, k):
    friends = list(range(1, n+1))
    index = 0
    while len(friends) > 1:
        index = (index + k - 1) % len(friends)
        friends.pop(index)

    return friends[0]

n = 5
k = 2

winner = find_winner(n, k)
print(f"The winner is friend number: {winner}")