# -*- coding: utf-8 -*-
"""TT Exp 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggrVExjxDptFll3HKbmxKjyJ5n_r7750
"""

def min_trips(boxes, max_boxes, max_weight):
    trips = 0
    current_boxes = 0
    current_weight = 0
    last_port = -1

    for port, num_boxes, weight in boxes:

        if current_boxes + num_boxes > max_boxes or current_weight + weight > max_weight:
            trips += 1
            current_boxes = 0
            current_weight = 0
            last_port = -1

        current_boxes += num_boxes
        current_weight += weight

        if port != last_port:
            trips += 1
            last_port = port

    if current_boxes > 0 or current_weight > 0:
        trips += 1

    return trips

boxes = [(1, 3, 10), (2, 4, 8), (1, 1, 5), (2, 2, 3)]
max_boxes = 5
max_weight = 15

result = min_trips(boxes, max_boxes, max_weight)
print(f"The minimum number of trips required: {result}")